### ISSUE TITLE
Pickle EpicVideoDataset object for distributed processing training

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#15]
Dear Will,

Is there a way to pickle the `EpicVideoDataset` object?
I was trying to use that class with a code using Distributed Data Parallel, multiprocessing. I got an error along the lines of `Can't pickle object EpicVideoDataset`.

Is that related to the GULPReader? Do you know a workaround for that?

Any thoughts or pointer will be relevant.

Thanks!

**Comment by willprice** [comment]
Do you get more of an error than just "can't pickle object"? If not, write a script that just instantiate an `EpicVideoDataset` and runs `pickle.dump` on it to get more info. Pickle errors usually arise from use of lambda functions that are reference within the object hierarchy (perhaps [this line](https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/master/src/datasets/epic_dataset.py#L76) might be the cause)

**Comment by escorciav** [comment]
Thanks! Yes, it's that kind of error.

Aja, I didn't know about errors due to lambda. If so, it seems like implementing an Identity transform should fix the issue, no?

I will review that later.

**Comment by willprice** [comment]
Perhaps, if that's the only non pickleable object that is being serialised,
but there could be others.
