### ISSUE TITLE
How to test a pretrained model 

### ISSUE THREAD

**Issue by jeevana28** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#17]
I downloaded pretrained models and loaded them from check points in models folder 
```
python src/test.py \
    models/trn_rgb.ckpt \
    results/trn_rgb.pt \
    --split val 
```

But I get this error TypeError: __init__() got an unexpected keyword argument 'row_log_interval'

How should I load a pretrained models and test it? 

Thanks

**Comment by willprice** [comment]
Use the specified version of pytorch lightning in the environment.yaml file

**Comment by Aanisha** [comment]
I am getting the same error with pytorch-lightning 1.1.8.

**Comment by willprice** [comment]
Hi both,
I see the problem, the checkpoints have the PTL `Trainer` constructor arguments saved in them, which are from v0.9. PTL removed those constructor args and replaced them with new ones. I've added some code to `src/test.py` that updates the checkpoint cfg on load to rename these arguments. Let me know if you run into any issues. Apologies for the slow response.
