### ISSUE TITLE
Converting RGB idx to Flow Pandas SettingWithCopyWarning

### ISSUE THREAD

**Issue by sawyermade** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#2]
When running the src/convert_rgb_to_flow_frame_idxs.py I get a Pandas error and am not sure if it is actually causing a probelm?

> ~/GIT/C1-Action-Recognition-TSN-TRN-TSM(master*) » ./run_flow_convert.sh           smc@x86_64-conda-linux-gnu
src/convert_rgb_to_flow_frame_idxs.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[col] = convert_rgb_frame_to_flow_frame_idx(year_df[col], stride)
(epic100-models)

**Comment by willprice** [comment]
This can be safely ignored, I have refactored the program to no longer produce this error.

**Comment by willprice** [comment]
(The script produces the same result as it did previously, no need to re-run anything on your end)

**Comment by sawyermade** [comment]
Thanks a lot! I just wasnt sure if it was working right or not, better safe than sorry haha.
