### ISSUE TITLE
Horizontal flip not returning flipped images?

### ISSUE THREAD

**Issue by kiyoon** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#20]
https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/2b7fa1894656e71dc5f8935213396b12c01b2eef/src/transforms.py#L60-L76

It looks like `ret` is never returned, but instead the original images are returned. Can you check if the code may be not applying flip at all?

Additionally, `is_flow` in the `__call__` method seems to be never used.

**Comment by DWhettam** [comment]
Hi @kiyoon, thanks for pointing that out! I believe you are correct. We use transforms from the [TSN codebase](https://github.com/yjxiong/tsn-pytorch/blob/master/transforms.py), which had the same issue, although now [seem to have been fixed](https://github.com/yjxiong/tsn-pytorch/issues/20). 

I'll update the code and test it all works, but for now you should be able to replace the function with the version in the TSN codebase.

**Comment by DWhettam** [comment]
Fixed via #21, closing this issue

**Comment by kiyoon** [comment]
Thanks for the prompt update!

You can also remove the `is_flow` in the `__call__` method which does nothing and just creates more confusion. That has to be defined in `__init__` instead.
