### ISSUE TITLE
Minor inconsistency in the gulp adaptor.

### ISSUE THREAD

**Issue by kiyoon** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#22]
Hi, I found that in the RGB gulp adaptor, the `stop_frame` is inclusive.
https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/e8e1a791944305c33adef09a966c51c0dfef0d38/src/utils/gulp_adapter.py#L75

whereas in the flow adaptor, the `stop_frame` is excluded.
https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/e8e1a791944305c33adef09a966c51c0dfef0d38/src/utils/gulp_adapter.py#L120

I know that it makes little difference, but just wanted to point it out because I found it when I was adapting the code to my training pipeline and I had an error trying to read one more frame.

**Comment by dimadamen** [comment]
Thanks for noting that :-)
