### ISSUE TITLE
How can I change the frame rate for training and evaluation?

### ISSUE THREAD

**Issue by qwangku** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#23]
Thanks for the datasets and pytorch codes.  I have a question about how to change the frame rate during training/evaluation.
I am looking at tsn_rgb.yaml right now. Which attribute in this config file controls the frame rate?  For example,  if I want to lower the frame rate for action recognition (predict based on fewer frames for a segment), how should I modify the yaml file or python code?

**Comment by dimadamen** [comment]
This code does *not* use a fixed frame rate. Instead, we use the same approach as TSN with a sparse set of K frames per action. If you would like a fixed frame rate codebase, you should look elsewhere.

If you want to understand how to sample frames, or change the number of frames, refer to the original TSN codebase: https://github.com/yjxiong/tsn-pytorch
