### ISSUE TITLE
Is the accuracy based on each batch or the entire val dataset?

### ISSUE THREAD

**Issue by qwangku** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#24]
Thanks for sharing this great repo. I am looking at https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/master/src/systems.py#L265, and I am trying to understand for the accuracy values were obtained.  According to line 265, it seems the accuracy values are calculated based on only single batch, instead of the entire validation dataset (I didn't find accumulation operation, either).  Can you confirm if acc_1 and acc_5 are for single batch or the entire validation dataset?

**Comment by DWhettam** [comment]
The line you referenced is indeed calculating the accuracy for each batch, as is standard whilst training. Once you've trained your model if you want a proper evaluation on the validation set see you should generate predictions on the val set (https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/tree/e8e1a791944305c33adef09a966c51c0dfef0d38#testing), and then you can evaluate using our script here: https://github.com/epic-kitchens/C1-Action-Recognition#evaluating-model-results

**Comment by qwangku** [comment]
Hi @DWhettam Thanks for confirming this.  I am trying to calculate the per-class accuracy for epic-kitchens-100 based on confusion matrix (i.e.  using validation_epoch_end function).  Currently, for validation on 97 verb classes,  I got an overall accuracy of 0.45 (which makes sense to me). However, the per-class accuracies I got is really sparse and the accuracies for a lot of classes are close to zero.  Is this expected?  I mean, is it possible that some verb classes actually don't exist in the validation data, or you also expect the accuracy for some specific classes to be very low?

**Comment by dimadamen** [comment]
I suggest you review this paper where we showed models fail miserably on tail classes: https://arxiv.org/pdf/1908.00867
While this is for epic-kitchens-55, the same stands. Yes, most tail classes achieve 0 performance, despite the presence of examples, using standard models. This is why we particularly evaluate for tail classes.
