### ISSUE TITLE
Download link for TSM features not working 

### ISSUE THREAD

**Issue by aleflabo** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#26]
Hi! 

I'm trying to download the RGB features extracted with TSM, but the link seems broken. 
Do you have an alternative one or should I just wait?

Thanks in advance.

Kind regards,
Alessandro

**Comment by dimadamen** [comment]
Due to some problems with dropbox, the public links have been disabled for 24 hours - due to huge downloads. Please try tomorrow and it should be fixed. Unfortunately we cannot fix it immediately,

**Comment by aleflabo** [comment]
Thank you for the quick answer. I'll wait until tomorrow, then!
