### ISSUE TITLE
mean and std have the same values in the checkpoints RGB

### ISSUE THREAD

**Issue by bguetarni** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#6]
Hi,
I downloaded the TSN (RGB) checkpoint to test it. After looking at the configuration attributes I saw that the **mean** and the **std** values for data pre-processing were actually the same. It is on purpose ?

If I do:
`ckpt = torch.load("path/to/tosn_rgb.ckpt", map_location=lambda storage, loc: storage)`
`cfg = OmegaConf.create(ckpt["hyper_parameters"])`
`OmegaConf.set_struct(cfg, False)`
`cfg.data._root_gulp_dir = os.getcwd()`
`print(cfg.data.preprocessing.mean)`
`print(cfg.data.preprocessing.std)`

Then I have:
`'mean': [0.485, 0.456, 0.406]`
`'std': [0.485, 0.456, 0.406]`

Actually after looking at the checkpoints of TRN and TMN I saw that they also have this problem.
Thanks.

**Comment by willprice** [comment]
Yes, that looks wrong to me, I'm fairly sure I didn't train them that way; good catch! I think I must have messed up the checkpoint conversion. 

The standard deviation should be `[0.229, 0.224, 0.225]`  for RGB models and the mean of that list for flow models.
Sorry about that.

I'll fix the checkpoints on dropbox by the end of next Tuesday and upload new checkpoints.

Thank you for the bug report.

**Comment by willprice** [comment]
Hi @bguetarni,
This has been rectified in d58e69562affdcdc1e40607ebaa0a954d4034cbf and the models have also been updated, you should find that if you redownload them (same URLs as before), then the `std` property will be correct.
Thanks again for raising the issue!

**Comment by willprice** [comment]
Hi @bguetarni,
It turns out I was mistaken and I did in fact train these models with the same mean and std, see https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/issues/8 for more details. I've reverted the checkpoints to their original variants.
