### ISSUE TITLE
Error launching training

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#7]
Hi,

I got [this error](https://drive.google.com/file/d/1_VAMRI984biOa7t26oPrGWMIijTSMqH9/view?usp=sharing) trying to launch the training. **Could you please provide a pointer on how to debug that?**

- I'm new to PytorchLighting. It seems that it modularizes the code too much.

- I couldn't reach the function or class returning the wrong data type.

_Details_

The output of my shell

```bash
$ ls _root_gulp_dir
flow_test  flow_validation  flow_train  rgb_test  rgb_validation  rgb_train
```

BTW, I already visualize the data

**Comment by willprice** [comment]
Try deleting [this line](https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/master/src/systems.py#L199) .

If you have errors, wrap [this line](https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/master/src/train.py#L33) with `with launch_ipdb_on_exception():`
after putting `from ipdb import launch_ipdb_on_exception` at the top of the file

**Comment by escorciav** [comment]
That made it 👍 . At least, I got a memory error 😅 .

- Thanks for the tip. I didn't use it after removing the line that you mentioned.
- May I know the purpose of the code block that I had to remove?
- BTW, do you know a simple trick to redirect stderr into `train.log`?

**Comment by willprice** [comment]
it just is an example input fed to the network to determine the input / output shapes of the modules printed when the training run begings.

> BTW, do you know a simple trick to redirect stderr into train.log?
Nope, have a look at the hydra docs, they might be able to help

**Comment by escorciav** [comment]
For me, you can close the issue. I don't do it as you might wanna use it as a reference before you push a "fix".
