### ISSUE TITLE
Are frames values in VideoRecord 1-indexed?

### ISSUE THREAD

**Issue by escorciav** [epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM#9]
Dear Will,

Could you please confirm that the frame values in `record.metadata` is 1-indexed?
I have that impression.

Thanks in advance!

**Comment by escorciav** [comment]
BTW, kindly point to me where you set the `record.metadata`.

I guess the code does that when dumping the gulp files. I'm rather asking for the code that does that. Perhaps, you add a nice comment as in other parts of the code.

Cheers!

**Comment by willprice** [comment]
Which frames values is that? I don't believe so... I think it's 0 indexed.

The gulp adapter just converts the annotation dataframe into a list of dictionaries: https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/731db0d5f3fed2e2f06b0ac7c1c01ade86d0baea/src/utils/gulp_adapter.py#L50 so it should just be passing through the annotation dataframe (https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/731db0d5f3fed2e2f06b0ac7c1c01ade86d0baea/src/gulp_data.py#L55)

I note that https://github.com/epic-kitchens/epic-kitchens-100-annotations doesn't actually specify whether the frame indices are 0 or 1 indexed, but looking back through our pipeline it seems they are 0-indexed. I'll add a note to the annotations repository

**Comment by escorciav** [comment]
I see. In other words,

- [`record.metadata`](https://github.com/epic-kitchens/C1-Action-Recognition-TSN-TRN-TSM/blob/731db0d5f3fed2e2f06b0ac7c1c01ade86d0baea/src/datasets/tsn_dataset.py#L72) is simply the columns of the files in the epic-kitchens-100 annotations.

It's fine whether is 0 or 1-indexed. I thought that it was 1-indexed as I think that the frames start with `1.jpg`. Maybe, the gulp is 0-indexed.

Thanks!

**Comment by willprice** [comment]
> record.metadata is simply the columns of the files in the epic-kitchens-100 annotations.
Correct
